API_URL = "https://api.mandaty.cz/"
EXCLUDE_ELECTIONS = "volby"
LOCALE = "cs"
API_DARUJME = "https://projects.kohovolit.eu/api/?projectId=1200738"
URL_DARUJME = "https://www.darujme.cz/projekt/1200738"
